--Based
require('core.mappings')
require("core.plugins")
require("core.configs")
require("core.colors")
--Plugins
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.mason")
require("plugins.telescope")
require("plugins.auto-pairs")
